apiVersion: apps/v1
kind: Deployment
metadata:
  name: acest-fitness
  labels:
    app: acest-fitness
spec:
  replicas: 2
  selector:
    matchLabels:
      app: acest-fitness
  template:
    metadata:
      labels:
        app: acest-fitness
    spec:
      containers:
      - name: acest-fitness
        image: amruta111/acest-fitness:latest
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
